# Procesamiento de lenguaje natural

## Importar paquetes

In [31]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.svm import SVC

from bs4 import BeautifulSoup
import re

sns.set_style('darkgrid')

In [32]:
df = pd.read_csv("./data/IMDB Dataset.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str
 1   sentiment  50000 non-null  str
dtypes: str(2)
memory usage: 781.4 KB

In [33]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [34]:
df.sample(5)

                                                  review sentiment
44054  Sure, it's a 50's drive-in special, but don't ...  positive
38176  I've tried to reconcile why so many bad review...  positive
11886  Like many people in my general age range, I re...  negative
37219  I agree with Vince, this movie paved the way f...  positive
32246  This is not a movie. This is a collection of r...  negative

In [35]:
df_pos = df[df['sentiment']=='positive'][:5000]
df_neg = df[df['sentiment']=='negative'][:5000]

df_reviews = pd.concat([df_pos, df_neg ])

In [36]:
from sklearn.model_selection import train_test_split

In [ ]:
train, test = train_test_split(df_reviews,test_size =0.33,random_state=42)

In [86]:
train_x, train_y = train['review'], train['sentiment']
test_x, test_y = test['review'], test['sentiment']

In [39]:
train_y.value_counts()

sentiment
negative    3378
positive    3322
Name: count, dtype: int64

Se usará TF-IDF, que es una técnica que combina:

- Term Frequency (TF): Frecuencia de un término en un documento, que mide la importancia del término en el documento en cuestión.

- Inverse Document Frequency (IDF): Mide la importancia del término en lque a colección de documentos. Penaliza los términos que son muy comunes en todos los documentos.

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [87]:
tfidf = TfidfVectorizer(stop_words='english')
train_x_vector = tfidf.fit_transform(train_x)
test_x_vector = tfidf.transform(test_x)

In [42]:
train_x.shape

(6700,)

In [43]:
train_x_vector.shape

(6700, 44107)

El tipo de dato scipy.sparse._csr.csr_matrix es una representación eficiente de una matriz dispersa en formato CSR (Compressed Sparse Row), que se utiliza para almacenar y manipular matrices grandes y dispersas.

In [44]:
type(train_x_vector)

scipy.sparse._csr.csr_matrix

## Trabajando la matriz dispersa

In [45]:
primera_resenia = pd.DataFrame.sparse.from_spmatrix(train_x_vector,
                                  index=train_x.index,
                                  columns=tfidf.get_feature_names_out()).iloc[0]
primera_resenia

00           NaN
000          NaN
007          NaN
00am         NaN
00s          NaN
            ...
ísnt         NaN
île          NaN
önsjön       NaN
über         NaN
überwoman    NaN
Name: 6746, Length: 44107, dtype: Sparse[float64, nan]

In [46]:
train_x.iloc[0]

"I happened to rent this movie with my sister in hopes of watching a great entertaining movie, that was humorous, however my expectations were let down. This movie was beyond disgusting and revolting for a PG-13 movie, this should have been rated R for the many mature references that went on in this movie. I wouldn't recommend allowing a 13 year old teen see this.<br /><br />Even if no one under the age of 17 is watching this movie, beware of a truly stupid movie, there's no humor in the movie, just a bunch of disgusting sexual references including a small touch of pedophilia, something that shouldn't even be joked about. <br /><br />I would like to know what happened to PG-13 movies, that were actually safe for actual a 13 year old? This is beyond a deplorable movie and should be re-rated."

In [50]:
primera_resenia[primera_resenia > 0]

13               0.45849
17               0.12824
actual          0.091601
actually        0.061461
age             0.088765
allowing         0.12824
beware          0.143046
br              0.124945
bunch           0.093128
deplorable      0.168137
disgusting      0.237945
entertaining    0.081088
expectations    0.103149
great           0.048868
happened        0.176853
hopes           0.114028
humor           0.084465
humorous        0.116516
including       0.087603
joked           0.168137
just            0.037675
know            0.053984
let              0.07195
like            0.036454
mature          0.126021
movie           0.276309
movies            0.0522
old             0.123513
pedophilia      0.172712
pg              0.260154
rated           0.206643
recommend       0.076198
references      0.226901
rent            0.093234
revolting       0.151971
safe            0.119732
sexual          0.098677
shouldn         0.108203
sister          0.095008
small           0.078916
stupid          0.079022
teen            0.109104
touch           0.103496
truly           0.078241
watching        0.118602
went            0.080113
wouldn          0.087362
year            0.149022
Name: 6746, dtype: Sparse[float64, nan]

In [48]:
train_x.iloc[0]

"I happened to rent this movie with my sister in hopes of watching a great entertaining movie, that was humorous, however my expectations were let down. This movie was beyond disgusting and revolting for a PG-13 movie, this should have been rated R for the many mature references that went on in this movie. I wouldn't recommend allowing a 13 year old teen see this.<br /><br />Even if no one under the age of 17 is watching this movie, beware of a truly stupid movie, there's no humor in the movie, just a bunch of disgusting sexual references including a small touch of pedophilia, something that shouldn't even be joked about. <br /><br />I would like to know what happened to PG-13 movies, that were actually safe for actual a 13 year old? This is beyond a deplorable movie and should be re-rated."

## Máquinas de Soporte Vectorial o Máquinas de Vectores de Soporte

### Entrenamiento

In [51]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(train_x_vector, train_y)

SVC(kernel='linear')

In [67]:
print(svc.predict(tfidf.transform(['A good movie'])), "1.")
print(svc.predict(tfidf.transform(['An excellent movie'])), "2.")
print(svc.predict(tfidf.transform(['I did not like this movie at all I gave this movie away'])), "3.")

print(svc.predict(tfidf.transform(['Not the movie I was waiting for'])), "4. ")
print(svc.predict(tfidf.transform(['This is the movie I was waiting for years'])), "5. ")
print(svc.predict(tfidf.transform(['This is the movie of the year'])), "6. ")

print(svc.predict(tfidf.transform(['It was horrible'])), "7. ")
print(svc.predict(tfidf.transform(['The worst I have seen in my life'])), "7. ")
print(svc.predict(tfidf.transform(['It would be better'])), "7. ")
print(svc.predict(tfidf.transform(['It is better than the last'])), "7. ")

['positive'] 1.
['positive'] 2.
['negative'] 3.
['negative'] 4.
['negative'] 5.
['positive'] 6.
['negative'] 7.
['negative'] 7.
['negative'] 7.
['negative'] 7.

El comando svc.score(test_x_vector, test_y) calcula la precisión del modelo SVM que acabamos de entrenar.

### Scores

In [ ]:
print(svc.score(test_x_vector, test_y))

0.8706060606060606

In [69]:
from sklearn.metrics import f1_score

f1_score(test_y,svc.predict(test_x_vector),
          labels = ['positive','negative'],average=None)

array([0.87400413, 0.86701962])

### Reporte de clasificación
El comando **classification_report** genera un informe que muestra varias métricas clave para evaluar el rendimiento del modelo en la clasificación de reseñas como positivas o negativas. En este caso, el modelo tiene una precisión de 0.87 para la clase 'positive' y de 0.88 para la clase 'negative', lo que indica que es ligeramente más preciso al identificar reseñas negativas. El recall para 'positive' es 0.88, mientras que para 'negative' es 0.86, sugiriendo que el modelo es algo mejor capturando reseñas positivas. El F1-Score, que equilibra precisión y recall, es de 0.87 para ambas clases, reflejando un rendimiento uniforme. El soporte, que indica cuántas reseñas de cada tipo estaban en el conjunto de prueba, es de 1678 para 'positive' y 1622 para 'negative'. La precisión global del modelo es del 87%, lo que significa que acertó en el 87% de las predicciones en el conjunto de prueba. El promedio macro, que toma el promedio de las métricas sin considerar el tamaño de las clases, y el promedio ponderado, que sí considera el tamaño de las clases, ambos dan un valor de 0.87, confirmando que el modelo tiene un rendimiento equilibrado y consistente entre ambas clases.

In [70]:
from sklearn.metrics import classification_report

print(classification_report(test_y,
                            svc.predict(test_x_vector),
                            labels = ['positive','negative']))

              precision    recall  f1-score   support

    positive       0.87      0.88      0.87      1678
    negative       0.88      0.86      0.87      1622

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300

### Matriz de confusión
Una matriz de confusión es una herramienta para evaluar el rendimiento del modelo clasificando datos en categorías. En este caso, la matriz de confusión se ha generado para las clases 'positive' y 'negative', y el output es un array 2x2 que se interpreta de la siguiente manera:

In [81]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(test_y,
                           svc.predict(test_x_vector),
                           labels = ['positive', 'negative'])
conf_mat

array([[1481,  197],
       [ 230, 1392]])

## Logistic Regression

### Entrenamiento

In [72]:
from sklearn.linear_model import LogisticRegression

modelo_LogReg = LogisticRegression(max_iter=1000)
modelo_LogReg.fit(train_x_vector, train_y)

LogisticRegression(max_iter=1000)

In [73]:
print(modelo_LogReg.predict(tfidf.transform(['A good movie'])), "1.")
print(modelo_LogReg.predict(tfidf.transform(['An excellent movie'])), "2.")
print(modelo_LogReg.predict(tfidf.transform(['I did not like this movie at all I gave this movie away'])), "3.")

print(modelo_LogReg.predict(tfidf.transform(['Not the movie I was waiting for'])), "4. ")
print(modelo_LogReg.predict(tfidf.transform(['This is the movie I was waiting for years'])), "5. ")
print(modelo_LogReg.predict(tfidf.transform(['This is the movie of the year'])), "6. ")

print(modelo_LogReg.predict(tfidf.transform(['It was horrible'])), "7. ")
print(modelo_LogReg.predict(tfidf.transform(['The worst I have seen in my life'])), "7. ")
print(modelo_LogReg.predict(tfidf.transform(['It would be better'])), "7. ")
print(modelo_LogReg.predict(tfidf.transform(['It is better than the last'])), "7. ")

['positive'] 1.
['positive'] 2.
['negative'] 3.
['negative'] 4.
['positive'] 5.
['positive'] 6.
['negative'] 7.
['negative'] 7.
['negative'] 7.
['negative'] 7.

### Scores

In [76]:
print(modelo_LogReg.score(test_x_vector, test_y))

0.8718181818181818

In [79]:
f1_score(test_y,modelo_LogReg.predict(test_x_vector),
          labels = ['positive','negative'],average=None)

array([0.87488909, 0.86859273])

### Reporte de clasificación

In [74]:
print(classification_report(test_y,
                            modelo_LogReg.predict(test_x_vector),
                            labels = ['positive','negative']))

              precision    recall  f1-score   support

    positive       0.87      0.88      0.87      1678
    negative       0.88      0.86      0.87      1622

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300

### Matriz de confusión

In [82]:
conf_mat_LogReg = confusion_matrix(test_y,
                           modelo_LogReg.predict(test_x_vector),
                           labels = ['positive', 'negative'])
conf_mat_LogReg

array([[1479,  199],
       [ 224, 1398]])

## Entrenamiento con GaussianNB

In [94]:
from sklearn.naive_bayes import GaussianNB

modelo_GaussianNB = GaussianNB()
modelo_GaussianNB.fit(train_x_vector.toarray(), train_y)

GaussianNB()

In [95]:
print(modelo_GaussianNB.predict(tfidf.transform(['A good movie']).toarray()), "1.")
print(modelo_GaussianNB.predict(tfidf.transform(['An excellent movie']).toarray()), "2.")
print(modelo_GaussianNB.predict(tfidf.transform(['I did not like this movie at all I gave this movie away']).toarray()), "3.")

print(modelo_GaussianNB.predict(tfidf.transform(['Not the movie I was waiting for']).toarray()), "4. ")
print(modelo_GaussianNB.predict(tfidf.transform(['This is the movie I was waiting for years']).toarray()), "5. ")
print(modelo_GaussianNB.predict(tfidf.transform(['This is the movie of the year']).toarray()), "6. ")

print(modelo_GaussianNB.predict(tfidf.transform(['It was horrible']).toarray()), "7. ")
print(modelo_GaussianNB.predict(tfidf.transform(['The worst I have seen in my life']).toarray()), "8. ")
print(modelo_GaussianNB.predict(tfidf.transform(['It would be better']).toarray()), "9. ")
print(modelo_GaussianNB.predict(tfidf.transform(['It is better than the last']).toarray()), "10. ")

['negative'] 1.
['negative'] 2.
['negative'] 3.
['negative'] 4.
['negative'] 5.
['negative'] 6.
['negative'] 7.
['negative'] 8.
['negative'] 9.
['negative'] 10.

### Scores

In [99]:
print(modelo_GaussianNB.score(test_x_vector.toarray(), test_y))

0.6427272727272727

In [100]:
f1_score(test_y,modelo_GaussianNB.predict(test_x_vector.toarray()),
          labels = ['positive','negative'],average=None)

array([0.6366718, 0.6485842])

### Reporte de clasificación

In [101]:
print(classification_report(test_y,
                            modelo_GaussianNB.predict(test_x_vector.toarray()),
                            labels = ['positive','negative']))

              precision    recall  f1-score   support

    positive       0.66      0.62      0.64      1678
    negative       0.63      0.67      0.65      1622

    accuracy                           0.64      3300
   macro avg       0.64      0.64      0.64      3300
weighted avg       0.64      0.64      0.64      3300

### Matriz de confusión

In [ ]:
conf_mat_GaussNB = confusion_matrix(test_y,
                           modelo_GaussianNB.predict(test_x_vector.toarray()),
                           labels = ['positive', 'negative'])
conf_mat_GaussNB

array([[1033,  645],
       [ 534, 1088]])

## Entrenamiento con Decision Tree Clasifier

In [103]:
from sklearn.tree import DecisionTreeClassifier
modelo_tree = DecisionTreeClassifier(random_state=42)
modelo_tree.fit(train_x_vector, train_y)

DecisionTreeClassifier(random_state=42)

In [104]:
print(modelo_tree.predict(tfidf.transform(['A good movie']).toarray()), "1.")
print(modelo_tree.predict(tfidf.transform(['An excellent movie']).toarray()), "2.")
print(modelo_tree.predict(tfidf.transform(['I did not like this movie at all I gave this movie away']).toarray()), "3.")

print(modelo_tree.predict(tfidf.transform(['Not the movie I was waiting for']).toarray()), "4. ")
print(modelo_tree.predict(tfidf.transform(['This is the movie I was waiting for years']).toarray()), "5. ")
print(modelo_tree.predict(tfidf.transform(['This is the movie of the year']).toarray()), "6. ")

print(modelo_tree.predict(tfidf.transform(['It was horrible']).toarray()), "7. ")
print(modelo_tree.predict(tfidf.transform(['The worst I have seen in my life']).toarray()), "8. ")
print(modelo_tree.predict(tfidf.transform(['It would be better']).toarray()), "9. ")
print(modelo_tree.predict(tfidf.transform(['It is better than the last']).toarray()), "10. ")

['positive'] 1.
['positive'] 2.
['positive'] 3.
['positive'] 4.
['positive'] 5.
['positive'] 6.
['negative'] 7.
['negative'] 8.
['positive'] 9.
['positive'] 10.

### Scores

In [106]:
print(modelo_tree.score(test_x_vector, test_y))

0.7163636363636363

In [107]:
f1_score(test_y,modelo_tree.predict(test_x_vector),
          labels = ['positive','negative'],average=None)

array([0.71807229, 0.71463415])

### Reporte de clasificación

In [108]:
print(classification_report(test_y,
                            modelo_tree.predict(test_x_vector),
                            labels = ['positive','negative']))

              precision    recall  f1-score   support

    positive       0.73      0.71      0.72      1678
    negative       0.71      0.72      0.71      1622

    accuracy                           0.72      3300
   macro avg       0.72      0.72      0.72      3300
weighted avg       0.72      0.72      0.72      3300

### Matriz de confusión

In [109]:
conf_mat_Tree = confusion_matrix(test_y,
                           modelo_tree.predict(test_x_vector),
                           labels = ['positive', 'negative'])
conf_mat_Tree

array([[1192,  486],
       [ 450, 1172]])

En conclusión, el modelo de Logistic Regression mostró el mejor desempeño tras haber predecido de manera más precisa diferentes reseña de prueba, presentando una ligera mejora en la precisión y matriz de confusión respecto al modelo de Máquinas de Soporte Vectorial.